name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Butler
        uses: jdno/setup-butler@v1

      - name: Push build
        run: butler push dist ermilburn02/vimjam4:web --userversion ${{ env.GITHUB_SHA }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_KEY }}
